version: '3.8'

services:
  api:
    container_name: cloud_store_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: 
      - .env.docker
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/cloud_store
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    container_name: cloud_store_db
    image: mysql:8.0
    env_file: 
      - .env.docker
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local