apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql/configmap.yaml
- mysql/service.yaml
- mysql/statefulset.yaml
- app/deployment.yaml
- app/service.yaml

commonLabels:
  app.kubernetes.io/part-of: cloudstore