name: Develop CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: cloud_store_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements/dev.txt
      
      - name: Run tests
        env:
          FLASK_ENV: testing
          DATABASE_URL: mysql+pymysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@127.0.0.1/cloud_store_test
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          python -m pytest -v --cov=app --cov-report=xml backend/tests/

  build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_CLOUD_STORE }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:dev-${{ github.sha }}
            ghcr.io/${{ github.repository }}:dev-latest
      
      - name: Update k8s manifest
        run: |
          cd k8s/overlays/develop
          sed -i "s/newTag: .*/newTag: dev-${{ github.sha }}/" kustomization.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kustomization.yaml
          git commit -m "chore: update image tag to dev-${{ github.sha }}"
          git push