name: Python Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: cloud_store_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt

    - name: Wait for MySQL
      run: |
        timeout 20 bash -c "until mysql -h 127.0.0.1 -u root -prootpassword -e 'SELECT 1'; do sleep 1; done"
    
    - name: Run tests
      env:
        FLASK_ENV: testing
        DATABASE_URL: mysql+pymysql://root:rootpassword@localhost:3306/cloud_store_test
        SECRET_KEY: test-key
      run: |
        python -m pytest tests/ -v --cov --cov-report=xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: success()
